language: ruby

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - MESSAGEBROKERNODEINSTANCETYPE=t2.small
  
before_install:
  - echo "Installing AWS CLI"
  - pip install --upgrade --user awscli
  - echo "Installing test gems"
  - gem install yaml-lint
  
install: true

script:
  - aws cloudformation validate-template --template-body file://templates/api_proxy.template
  - aws cloudformation validate-template --template-body file://templates/Security/proxy_endpoint.template
  - aws cloudformation validate-template --template-body file://templates/Security/proxy_role.template
  - aws cloudformation validate-template --template-body file://templates/Security/proxy_securityGroup.template
  - aws cloudformation validate-template --template-body file://templates/Services/kinesis_proxy.template
  - aws cloudformation validate-template --template-body file://templates/Services/resource_proxy.template
  - aws cloudformation validate-template --template-body file://templates/Services/s3_proxy.template
  - aws cloudformation validate-template --template-body file://templates/Solace/node_create.template
  - yaml-lint -n templates/
  - yaml-lint -n templates/Services
  - yaml-lint -n templates/Security
  - yaml-lint -n templates/Solace

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation templates validated"
  - echo "YAML linted"
  - echo "Cloudformation tested"
  - echo "Messaging tested"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then aws s3 sync . s3://solace-labs/solace-aws-service-integration/latest --acl public-read; fi

after_script:
