language: ruby

env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - NODE_INSTANCE_TYPE=t2.large
  - TRAVIS_S3_BUCKET=solace-travis-test
  - TRAVIS_S3_PREFIX=solace-aws-service-integration/latest
  
before_install:
  - echo "Installing AWS CLI"
  - pip install --upgrade --user awscli
  - pip install --upgrade --user jq
  - echo "Installing test gems"
  - gem install yaml-lint

install: true

script:
  - aws cloudformation validate-template --template-body file://templates/api_proxy.template
  - aws cloudformation validate-template --template-body file://templates/Security/proxy_endpoint.template
  - aws cloudformation validate-template --template-body file://templates/Security/proxy_role.template
  - aws cloudformation validate-template --template-body file://templates/Security/proxy_securityGroup.template
  - aws cloudformation validate-template --template-body file://templates/Services/kinesis_proxy.template
  - aws cloudformation validate-template --template-body file://templates/Services/resource_proxy.template
  - aws cloudformation validate-template --template-body file://templates/Services/s3_proxy.template
  - aws cloudformation validate-template --template-body file://templates/Solace/node_create.template
  - yaml-lint -n templates/
  - yaml-lint -n templates/Services
  - yaml-lint -n templates/Security
  - yaml-lint -n templates/Solace
  - sed -i "s@SOLOS_PASSWORD@$SOLOS_PASSWORD@g" ci/travis-test-sqs.json
  - sed -i "s@TEST_KEYPAIR@$TEST_KEYPAIR@g" ci/travis-test-sqs.json
  - sed -i "s@NODE_INSTANCE_TYPE@$NODE_INSTANCE_TYPE@g" ci/travis-test-sqs.json
  - sed -i "s@SQS_ARN@$SQS_ARN@g" ci/travis-test-sqs.json
  - sed -i "s@TEST_SECURITY_GROUP_ID@$TEST_SECURITY_GROUP_ID@g" ci/travis-test-sqs.json
  - sed -i "s@TEST_SUBNET_ID@$TEST_SUBNET_ID@g" ci/travis-test-sqs.json
  - sed -i "s@TEST_VPC_ID@$TEST_VPC_ID@g" ci/travis-test-sqs.json
  - sed -i "s@TRAVIS_S3_BUCKET@$TRAVIS_S3_BUCKET@g" ci/travis-test-sqs.json
  - sed -i "s@TRAVIS_S3_PREFIX@$TRAVIS_S3_PREFIX@g" ci/travis-test-sqs.json
  - aws s3 mb s3://$TRAVIS_S3_BUCKET || echo "s3 bucket already existed"
  - aws s3 sync . s3://$TRAVIS_S3_BUCKET/$TRAVIS_S3_PREFIX --acl public-read
  - export TESTSTACKPREFIX="T$(date +%s)"; export TESTSTACKNAME="$TESTSTACKPREFIX-service-integration";
  - cat ci/travis-test-sqs.json
  - aws cloudformation create-stack --stack-name $TESTSTACKNAME --template-body file://templates/api_proxy+vmr.template --parameters file://ci/travis-test-sqs.json  --disable-rollback --capabilities  CAPABILITY_NAMED_IAM
  - echo "Waiting for stack create complete"
  - "travis_wait 30 sleep 1800 &"
  - until aws cloudformation describe-stacks --stack-name $TESTSTACKNAME | grep -m 1 -E 'CREATE_COMPLETE|DELETE_IN_PROGRESS'; do sleep 10; done
  - aws cloudformation describe-stack-events --stack-name $TESTSTACKNAME
  - aws cloudformation describe-stacks --stack-name $TESTSTACKNAME
  - solaceStackName="$(aws cloudformation describe-stack-resource --stack-name $TESTSTACKNAME --logical-resource-id  SolaceStack | grep -oE "$TESTSTACKNAME-SolaceStack-[0-9A-Z]*")"
  - solaceStackJson="$(aws cloudformation describe-stack-resource --stack-name $solaceStackName  --logical-resource-id NodeLaunchConfig)"
  - instanceId="$(jq '.StackResourceDetail.PhysicalResourceId' <<< $solaceStackJson)"
  - instanceInfo="$(aws ec2 describe-instances --region us-east-1 --instance-ids $instanceId )"
  - dns="$(jq '.Reservations[0].Instances[0].NetworkInterfaces[0].Association.PublicDnsName' <<< $instanceInfo)"
  - echo $dns
  - curl -O https://sftp.solace.com/download/SDKPERF_C_LINUX64
  - tar -xvf SDKPERF_C_LINUX64
  - pubSubTools/sdkperf_c -cip=$dns -mn=100000 -mr=0 -ptl=t1 -stl=t1 | grep "Total Messages"

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation templates validated"
  - echo "YAML linted"
  - echo "Cloudformation tested"
  - echo "Messaging tested"
  - if [ "$TRAVIS_BRANCH" = "master" ]; then aws s3 sync . s3://solace-labs/$TRAVIS_S3_PREFIX --acl public-read; fi

after_script:
after_script:
  - aws s3 rb s3://$TRAVIS_S3_BUCKET --force
  - aws cloudformation delete-stack --stack-name $TESTSTACKNAME
  - echo "Waiting for stack delete complete"
  - stackid="$(aws cloudformation describe-stacks --stack-name $TESTSTACKNAME | grep StackId | awk -F '"' '{print $4}')"
  - if [ -n "$stackid" ]; then until aws cloudformation describe-stacks --stack-name $stackid | grep -m 1 "DELETE_COMPLETE"; do sleep 10; done; fi